# Archivo: render.yaml (Va junto a tu pom.xml)
services:
  - type: web
    name: tenbi-backend
    env: docker  # Mantiene la selecci칩n de "Docker" en la UI de Render
    # Comandos de compilaci칩n y ejecuci칩n de Maven/Java
    buildCommand: "mvn clean install -DskipTests"
    startCommand: "java -jar target/*.jar"
    
    # Ruta para que Render verifique que la app est치 viva
    healthCheckPath: "/actuator/health"
